const VOICE_CHROME = {
  IDLE: 'VOICE_CHROME_IDLE',
  LOCAL_LISTENING: 'VOICE_CHROME_LOCAL_LISTENING',
  LISTENING: 'VOICE_CHROME_LISTENING',
  STOP_LISTENING: 'VOICE_CHROME_STOP_LISTENING',
  THINKING: 'VOICE_CHROME_THINKING',
  SPEAKING: 'VOICE_CHROME_SPEAKING',
  ERROR: 'VOICE_CHROME_ERROR'
}

export default VOICE_CHROME
